// frontend/src/app/pages/login/login-page.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';
import { ToastService } from '../../core/services/toast.service';

@Component({
  standalone: true,
  selector: 'app-login-page',
  imports: [CommonModule, FormsModule],
  template: `
    <section class="auth-grid">
      <article class="panel auth-aside fade-up">
        <p class="section__eyebrow">BLACK COFFE</p>
        <h1 class="section__title">{{ mode === 'login' ? 'Bienvenido' : 'Nueva cuenta' }}</h1>
        <p class="section__copy">Más que una bebida... es un estilo de vida.</p>
        <p class="section__copy section__copy--small">
          {{ mode === 'login'
            ? 'Ingresa con tu cuenta para ver perfil, pedidos y reservas.'
            : 'Crea tu cuenta para comenzar a pedir desde el menú interactivo.' }}
        </p>
        <button *ngIf="mode === 'login'" class="btn btn-outline" type="button" (click)="useDemoAccount()">USAR DEMO</button>
      </article>

      <article class="panel auth-form fade-up" style="--delay: 80ms;">
        <h2 class="section__title section__title--md">{{ mode === 'login' ? 'Login' : 'Create Account' }}</h2>
        <form class="form" (ngSubmit)="submit()">
          <input *ngIf="mode === 'register'" [(ngModel)]="fullName" name="fullName" placeholder="Nombre completo" required />
          <input [(ngModel)]="email" name="email" type="email" placeholder="Email" required />
          <input *ngIf="mode === 'register'" [(ngModel)]="phone" name="phone" placeholder="Teléfono" required />
          <input [(ngModel)]="password" name="password" type="password" placeholder="Password" required />

          <div class="row-actions row-actions--stretch">
            <button class="btn" [disabled]="loading">{{ mode === 'login' ? 'INGRESAR' : 'CREAR CUENTA' }}</button>
            <button class="btn btn-outline" type="button" (click)="toggleMode()">
              {{ mode === 'login' ? 'IR A CREATE ACCOUNT' : 'VOLVER A LOGIN' }}
            </button>
          </div>
        </form>

        <p class="message" *ngIf="message">{{ message }}</p>
        <p class="message message--soft">Demo: {{ demoEmail }} / {{ demoPassword }}</p>
      </article>
    </section>
  `
})
export class LoginPageComponent {
  readonly demoEmail = 'julio.cesar.ticas.demo@blackcoffe.local';
  readonly demoPassword = 'DemoCafe123*';

  mode: 'login' | 'register' = 'login';
  fullName = '';
  email = this.demoEmail;
  phone = '';
  password = this.demoPassword;
  message = '';
  loading = false;

  constructor(
    private readonly auth: AuthService,
    private readonly router: Router,
    private readonly toast: ToastService
  ) {}

  toggleMode(): void {
    this.mode = this.mode === 'login' ? 'register' : 'login';
    this.message = '';
  }

  useDemoAccount(): void {
    this.mode = 'login';
    this.email = this.demoEmail;
    this.password = this.demoPassword;
    this.message = '';
  }

  async submit(): Promise<void> {
    this.loading = true;
    this.message = '';

    try {
      if (this.mode === 'login') {
        await this.auth.login({ email: this.email, password: this.password });
        this.message = 'Sesion iniciada.';
        this.toast.success(this.message);
        await this.router.navigateByUrl('/profile');
      } else {
        await this.auth.register({ fullName: this.fullName, email: this.email, phone: this.phone, password: this.password });
        this.message = 'Cuenta creada e inicio de sesion exitoso.';
        this.toast.success(this.message);
        await this.router.navigateByUrl('/profile');
      }
    } catch (error: any) {
      if (error?.status === 0) {
        this.message = 'No hay conexion con backend. Levanta primero la API en http://localhost:5088.';
        this.toast.error(this.message);
        return;
      }

      if (error?.status === 401) {
        this.message = 'Credenciales invalidas. Verifica correo y password.';
        this.toast.error(this.message);
        return;
      }

      if (error?.status === 503) {
        this.message = error?.error?.message ?? 'La base de datos no esta disponible en este momento.';
        this.toast.error(this.message);
        return;
      }

      this.message = error?.error?.message ?? error?.message ?? 'Error de autenticacion';
      this.toast.error(this.message);
    } finally {
      this.loading = false;
    }
  }
}

// storefront-next/src/components/pages/login-page.tsx
"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { PageHeader } from "@/components/shared/page-header";
import { apiClient } from "@/lib/api-client";
import { getErrorStatus, getErrorMessage } from "@/lib/error";
import { useAuthStore } from "@/store/auth-store";
import { useUiStore } from "@/store/ui-store";
import { useHydrated } from "@/hooks/use-hydrated";

const demoEmail = "julio.cesar.ticas.demo@blackcoffe.local";
const demoPassword = "DemoCafe123*";

export function LoginPage() {
  const hydrated = useHydrated();
  const router = useRouter();
  const auth = useAuthStore((state) => state.auth);
  const setAuth = useAuthStore((state) => state.setAuth);
  const pushToast = useUiStore((state) => state.pushToast);

  const [mode, setMode] = useState<"login" | "register">("login");
  const [fullName, setFullName] = useState("");
  const [email, setEmail] = useState(demoEmail);
  const [phone, setPhone] = useState("");
  const [password, setPassword] = useState(demoPassword);
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(false);

  async function submit() {
    setLoading(true);
    setMessage("");

    try {
      const response =
        mode === "login"
          ? await apiClient.login({ email, password })
          : await apiClient.register({ fullName, email, phone, password });

      setAuth(response);
      pushToast({
        tone: "success",
        title: mode === "login" ? "Sesion iniciada" : "Cuenta creada",
        description: mode === "login" ? "Tu perfil ya esta listo." : "Tu cuenta se creo e inicio sesion correctamente.",
      });
      router.push("/profile");
    } catch (error) {
      const status = getErrorStatus(error);
      const nextMessage =
        status === 401
          ? "Credenciales invalidas. Verifica correo y password."
          : status === 503
            ? getErrorMessage(error, "La base de datos no esta disponible en este momento.")
            : getErrorMessage(error, "Error de autenticacion.");
      setMessage(nextMessage);
      pushToast({ tone: "error", title: "No se pudo autenticar", description: nextMessage });
    } finally {
      setLoading(false);
    }
  }

  if (!hydrated) {
    return (
      <div className="page-container">
        <section className="section-panel animate-pulse p-8">
          <div className="h-3 w-20 rounded-full bg-white/10" />
          <div className="mt-5 h-8 w-72 rounded-full bg-white/10" />
          <div className="mt-8 h-72 rounded-[1.5rem] bg-white/8" />
        </section>
      </div>
    );
  }

  if (auth) {
    return (
      <div className="page-container">
        <section className="section-panel space-y-6 p-8 text-center">
          <p className="section-eyebrow">Mi cuenta</p>
          <h1 className="page-title mt-0">Ya tienes una sesion activa</h1>
          <p className="mx-auto max-w-2xl text-sm leading-7 text-white/62 sm:text-base">
            Continua a tu perfil para ver pedidos, reservas y datos de tu cuenta.
          </p>
          <div className="flex justify-center gap-3">
            <Link href="/profile" className="button-primary">Ir a perfil</Link>
            <Link href="/catalog" className="button-secondary">Ver menu</Link>
          </div>
        </section>
      </div>
    );
  }

  return (
    <div className="page-container grid gap-6 xl:grid-cols-[0.92fr_1.08fr]">
      <section className="section-panel p-8">
        <p className="section-eyebrow">Black Coffe</p>
        <h1 className="page-title mt-4">{mode === "login" ? "Bienvenido" : "Nueva cuenta"}</h1>
        <p className="muted-copy mt-3">Mas que una bebida... es un estilo de vida.</p>
        <p className="mt-6 text-sm leading-7 text-white/60">
          {mode === "login"
            ? "Ingresa con tu cuenta para ver perfil, pedidos y reservas."
            : "Crea tu cuenta para comenzar a pedir desde el menu interactivo y guardar tu historial."}
        </p>
        {mode === "login" ? (
          <button
            type="button"
            className="button-secondary mt-8"
            onClick={() => {
              setMode("login");
              setEmail(demoEmail);
              setPassword(demoPassword);
              setMessage("");
            }}
          >
            Usar demo
          </button>
        ) : null}
      </section>

      <section className="section-panel p-8">
        <PageHeader
          eyebrow={mode === "login" ? "Login" : "Create Account"}
          title={mode === "login" ? "Entrar" : "Crear cuenta"}
          description="Sin romper la API actual: este flujo sigue usando los mismos endpoints y el mismo JWT del backend .NET."
        />

        <form
          className="mt-8 space-y-4"
          onSubmit={(event) => {
            event.preventDefault();
            void submit();
          }}
        >
          {mode === "register" ? (
            <input className="input-field" value={fullName} onChange={(e) => setFullName(e.target.value)} placeholder="Nombre completo" required />
          ) : null}
          <input className="input-field" type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email" required />
          {mode === "register" ? (
            <input className="input-field" value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="Telefono" required />
          ) : null}
          <input className="input-field" type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Password" required />

          {message ? <p className="rounded-2xl border border-red-400/20 bg-red-400/10 px-4 py-3 text-sm text-red-200">{message}</p> : null}

          <div className="grid gap-3 sm:grid-cols-2">
            <button type="submit" className="button-primary w-full" disabled={loading}>
              {loading ? "Procesando" : mode === "login" ? "Ingresar" : "Crear cuenta"}
            </button>
            <button
              type="button"
              className="button-secondary w-full"
              onClick={() => {
                setMode((current) => (current === "login" ? "register" : "login"));
                setMessage("");
              }}
            >
              {mode === "login" ? "Ir a create account" : "Volver a login"}
            </button>
          </div>
        </form>

        <p className="mt-6 rounded-full border border-white/10 bg-white/[0.03] px-4 py-3 text-sm text-white/48">
          Demo: {demoEmail} / {demoPassword}
        </p>
      </section>
    </div>
  );
}
