// storefront-next/src/components/pages/cart-page.tsx
"use client";

import Link from "next/link";
import { EmptyState } from "@/components/shared/empty-state";
import { PageHeader } from "@/components/shared/page-header";
import { formatCurrency } from "@/lib/format";
import { getCartGrandTotal, getCartIvaAmount, getCartSubtotal, SHIPPING_COST, useCartStore } from "@/store/cart-store";
import { useUiStore } from "@/store/ui-store";
import { useHydrated } from "@/hooks/use-hydrated";

export function CartPage() {
  const hydrated = useHydrated();
  const items = useCartStore((state) => state.items);
  const increase = useCartStore((state) => state.increase);
  const decrease = useCartStore((state) => state.decrease);
  const remove = useCartStore((state) => state.remove);
  const clear = useCartStore((state) => state.clear);
  const pushToast = useUiStore((state) => state.pushToast);

  if (!hydrated) {
    return (
      <div className="page-container">
        <section className="section-panel animate-pulse p-8">
          <div className="h-3 w-20 rounded-full bg-white/10" />
          <div className="mt-5 h-8 w-72 rounded-full bg-white/10" />
          <div className="mt-8 h-52 rounded-[1.5rem] bg-white/8" />
        </section>
      </div>
    );
  }

  const subtotal = getCartSubtotal(items);
  const iva = getCartIvaAmount(items);
  const total = getCartGrandTotal(items);

  if (!items.length) {
    return (
      <div className="page-container">
        <EmptyState
          icon="cart"
          title="Tu carrito esta vacio"
          description="Agrega productos desde el menu para continuar con tu pedido y luego cerrar el checkout desde una sola interfaz."
          action={
            <Link href="/catalog" className="button-primary">
              Ver menu
            </Link>
          }
        />
      </div>
    );
  }

  return (
    <div className="page-container grid gap-6 xl:grid-cols-[1.25fr_0.75fr]">
      <section className="space-y-6">
        <PageHeader
          eyebrow="Carrito"
          title="Revisa tu pedido"
          description="Ajusta cantidades, elimina items o sigue comprando antes de pasar a checkout."
          actions={
            <Link href="/catalog" className="button-secondary">
              Seguir comprando
            </Link>
          }
        />

        <div className="space-y-4">
          {items.map((item) => (
            <article key={item.productId} className="section-panel flex flex-col gap-5 p-6 sm:flex-row sm:items-center sm:justify-between">
              <div>
                <h2 className="text-2xl font-semibold text-white">{item.name}</h2>
                <p className="mt-2 text-sm leading-7 text-white/58">{formatCurrency(item.unitPrice)} por unidad</p>
              </div>

              <div className="flex flex-col gap-4 sm:items-end">
                <strong className="text-xl text-[#ead7b3]">{formatCurrency(item.unitPrice * item.quantity)}</strong>
                <div className="flex items-center gap-3">
                  <div className="inline-flex items-center rounded-full border border-white/10 bg-white/[0.04] p-1">
                    <button
                      type="button"
                      className="grid size-9 place-items-center rounded-full text-white/80 hover:bg-white/10 hover:text-white"
                      onClick={() => decrease(item.productId)}
                    >
                      -
                    </button>
                    <span className="min-w-10 text-center text-sm font-semibold text-white">{item.quantity}</span>
                    <button
                      type="button"
                      className="grid size-9 place-items-center rounded-full text-white/80 hover:bg-white/10 hover:text-white"
                      onClick={() => increase(item.productId)}
                    >
                      +
                    </button>
                  </div>
                  <button
                    type="button"
                    className="button-secondary"
                    onClick={() => {
                      remove(item.productId);
                      pushToast({ tone: "info", title: "Producto eliminado" });
                    }}
                  >
                    Eliminar
                  </button>
                </div>
              </div>
            </article>
          ))}
        </div>
      </section>

      <aside className="section-panel h-fit p-6 xl:sticky xl:top-32">
        <p className="section-eyebrow">Resumen</p>
        <h2 className="mt-3 text-3xl font-semibold text-white">Totales</h2>
        <div className="mt-8 space-y-3 text-sm text-white/65">
          <div className="flex items-center justify-between">
            <span>Subtotal</span>
            <strong className="text-white">{formatCurrency(subtotal)}</strong>
          </div>
          <div className="flex items-center justify-between">
            <span>Envio</span>
            <strong className="text-white">{formatCurrency(SHIPPING_COST)}</strong>
          </div>
          <div className="flex items-center justify-between">
            <span>IVA 12%</span>
            <strong className="text-white">{formatCurrency(iva)}</strong>
          </div>
          <div className="flex items-center justify-between border-t border-white/10 pt-4 text-base">
            <span className="font-semibold text-white">Total</span>
            <strong className="text-[#ead7b3]">{formatCurrency(total)}</strong>
          </div>
        </div>

        <div className="mt-8 grid gap-3">
          <Link href="/checkout" className="button-primary w-full">
            Ir a checkout
          </Link>
          <button
            type="button"
            className="button-secondary w-full"
            onClick={() => {
              clear();
              pushToast({ tone: "info", title: "Carrito vaciado" });
            }}
          >
            Vaciar carrito
          </button>
        </div>
      </aside>
    </div>
  );
}

// frontend/src/app/pages/cart/cart-page.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { CartService } from '../../core/services/cart.service';
import { ToastService } from '../../core/services/toast.service';
import { IconComponent } from '../../shared/icon/icon.component';

@Component({
  standalone: true,
  selector: 'app-cart-page',
  imports: [CommonModule, RouterLink, IconComponent],
  template: `
    <section class="empty-state" *ngIf="items.length === 0">
      <app-icon name="cart" [size]="40" className="empty-state__icon"></app-icon>
      <p class="section__eyebrow">CARRITO</p>
      <h2 class="section__title section__title--md">Tu carrito esta vacio ☕</h2>
      <p class="section__copy">Agrega productos desde el menu para continuar con tu pedido.</p>
      <div class="row-actions justify-center">
        <a class="btn-primary" routerLink="/catalog">Ver menu</a>
      </div>
    </section>

      <section class="panel section" *ngIf="items.length > 0">
        <p class="section__eyebrow">CARRITO</p>
        <h1 class="section__title">Revisa tu pedido</h1>
        <p class="section__copy">Ajusta cantidades con controles rapidos y confirma en checkout.</p>

      <div class="cart-list">
        <article class="cart-line fade-up" *ngFor="let item of items; let i = index" [style.--delay]="(i * 45) + 'ms'">
          <div class="cart-line__main">
            <h3>{{ item.name }}</h3>
            <p>Q{{ item.unitPrice | number:'1.2-2' }} por unidad</p>
          </div>

          <div class="cart-line__actions">
            <div class="counter counter--line">
              <button class="counter__btn" type="button" (click)="decrease(item.productId)">-</button>
              <span class="counter__value">{{ item.quantity }}</span>
              <button class="counter__btn" type="button" (click)="increase(item.productId)">+</button>
            </div>
            <strong class="cart-line__subtotal">Q{{ (item.quantity * item.unitPrice) | number:'1.2-2' }}</strong>
            <button class="btn-outline btn-small" type="button" (click)="remove(item.productId)">Eliminar</button>
          </div>
        </article>
      </div>

      <div class="cart-summary-grid">
        <div class="cart-summary-row">
          <span>Subtotal</span>
          <strong>Q{{ subtotal | number:'1.2-2' }}</strong>
        </div>
        <div class="cart-summary-row">
          <span>Envio</span>
          <strong>Q{{ shipping | number:'1.2-2' }} (Gratis)</strong>
        </div>
        <div class="cart-summary-row">
          <span>IVA (12%)</span>
          <strong>Q{{ ivaAmount | number:'1.2-2' }}</strong>
        </div>
        <div class="cart-summary-row cart-summary-row--total">
          <span>Total</span>
          <strong>Q{{ total | number:'1.2-2' }}</strong>
        </div>
      </div>
    </section>

    <section class="cart-sticky" *ngIf="items.length > 0">
      <div class="cart-sticky__total">
        <strong>Total Q{{ total | number:'1.2-2' }}</strong>
        <span>{{ cart.totalItems }} {{ cart.totalItems === 1 ? 'item' : 'items' }}</span>
      </div>
      <div class="cart-sticky__actions">
        <a class="btn-outline" routerLink="/catalog">Seguir</a>
        <button class="btn-outline" type="button" (click)="clear()">Vaciar</button>
        <a class="btn-primary" routerLink="/checkout">Checkout</a>
      </div>
    </section>
  `
})
export class CartPageComponent {
  constructor(public readonly cart: CartService, private readonly toast: ToastService) {}

  get items() {
    return this.cart.snapshot;
  }

  get total() {
    return this.cart.grandTotal;
  }

  get subtotal() {
    return this.cart.subtotal;
  }

  get shipping() {
    return this.cart.shipping;
  }

  get ivaAmount() {
    return this.cart.ivaAmount;
  }

  remove(productId: string): void {
    this.cart.remove(productId);
    this.toast.success('Producto eliminado del carrito.');
  }

  increase(productId: string): void {
    this.cart.increase(productId);
  }

  decrease(productId: string): void {
    this.cart.decrease(productId);
  }

  clear(): void {
    this.cart.clear();
    this.toast.success('Carrito vaciado.');
  }
}
